name: Publish to NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run test
        env:
          CLIENT_ID: ${{ secrets.PAYPAL_SANDBOX_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PAYPAL_SANDBOX_CLIENT_SECRET }}
      # Publish to npm
      - run: npm run lib:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
